from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GuildActivityMonitorAssets:
	# OCR 活动关键字（ROI 先用全屏，后续再调整具体区域）
	O_GUILD_DOKAN = RuleOcr(
		roi=(181, 214, 268, 455),
		area=(181, 214, 268, 455),
		mode="Full",
		method="Default",
		keyword="道馆",
		name="guild_dokan"
	)
	O_GUILD_ABYSS = RuleOcr(
		roi=(181, 214, 268, 455),
		area=(181, 214, 268, 455),
		mode="Full",
		method="Default",
		keyword="狭间",
		name="guild_abyss"
	)
	O_GUILD_BANQUET = RuleOcr(
		roi=(181, 214, 268, 455),
		area=(181, 214, 268, 455),
		mode="Full",
		method="Default",
		keyword="宴会",
		name="guild_banquet"
	)
	O_GUILD_DEMON_RETREAT = RuleOcr(
		roi=(181, 214, 268, 455),
		area=(181, 214, 268, 455),
		mode="Full",
		method="Default",
		keyword="退治",
		name="guild_demon_retreat"
	)
